### ISSUE TITLE
[블로그 입력화면] UI 잘리는 현상, 검증 오류

### ISSUE THREAD

**Issue by NEULiee** [boostcampwm-2022/iOS09-burstcamp#216]
## 할 일

- [x] UI 잘리는 현상
- 의견: 검증할 때 키보드를 내려주는 것은 어떨까요?
<img src="https://user-images.githubusercontent.com/39167842/206827442-eca783b7-6ae5-4c6e-b4e3-185adef8585e.png" width=300>

- [ ] 무한히 로딩중

<img src="https://user-images.githubusercontent.com/39167842/206827425-168912d4-9018-4daa-a7d6-bfda3d32a5a0.png" width=300>

**Comment by Kim-Coding** [comment]
<img src="https://user-images.githubusercontent.com/54696445/207229048-073c9278-71c8-442a-b3c8-61a7de68dd3f.png" width=324>

**Comment by Kim-Coding** [comment]
indicator 사이즈 변경으로 해결
