### ISSUE TITLE
[마이페이지] 탈퇴

### ISSUE THREAD

**Issue by never-better** [boostcampwm-2022/iOS09-burstcamp#27]
## 할 일
- 탈퇴
    - [x]  탈퇴할지 한 번 더 확인하는 Alert (모든 데이터가 삭제된다는 내용추가)
    - [x]  한다고 하면 파이어베이스 DB에서 지우고 로그인 화면으로 이동
    - [x]  취소하면 페이지 유지

**Comment by NEULiee** [comment]
### 탈퇴시 정보를 잘 지워줘야한다.
- FireStore User
- FireStore Feed
- FireStoreFCM
- FirebaseAuthentication
- UserManager Singleton
- KeyChain User
