### ISSUE TITLE
[마이페이지] 알림 설정

### ISSUE THREAD

**Issue by Kim-Coding** [boostcampwm-2022/iOS09-burstcamp#28]
## 할 일

- [x] 알림 권한 설정
- [x] FCM 토큰 생성
- [x] FCM 토큰 DB 저장
- [x] 파이어베이스 알림 Funcion
    - 파이어 베이스 알림을 통해, DB에 새로운 피드 등록시 알림 옴
- [x] Coordinator 처리

**Comment by NEULiee** [comment]
## Firebase Functions

- [[등록 토큰을 대상으로 메시지를 지정](https://firebase.google.com/docs/cloud-messaging/send-message?authuser=1&hl=ko#send_messages_to_specific_devices)]

[[앱 서버 보내기 요청 빌드 | Firebase 클라우드 메시징](https://firebase.google.com/docs/cloud-messaging/send-message?authuser=1&hl=ko#send_messages_to_specific_devices)]

[[How to use Firebase Cloud functions to send push notifications](https://engineering.monstar-lab.com/en/post/2021/02/09/Use-Firebase-Cloudfunctions-To-Send-Push-Notifications/)]

### Node.js

```jsx
// Create a list containing up to 500 registration tokens.
// These registration tokens come from the client FCM SDKs.

// 가장 최근 feed 가져온다. / 발행 날짜가 오늘이 아니라면 종료 (firestore)
// isPushOn 이 true로 설정되어 있는 User uuid를 가져온다. (firestore)
// user uuid 가지고 FCM 토큰을 가져온다. (firestore)

// FCM 토큰 가지고 알림을 보낸다.
const registrationTokens = [
  'YOUR_REGISTRATION_TOKEN_1',
  // …
  'YOUR_REGISTRATION_TOKEN_N',
];

const message = {
	notification: {
      title: 'burstcamp',
      body: '메세지를 어떻게 보내야 할지요'
  },
  data: { feedUUID: 'asddqwdqwasdasdasd' },
  tokens: registrationTokens,
};

getMessaging().sendMulticast(message)
  .then((response) => {
    console.log(response.successCount + ' messages were sent successfully');
  });
```

### Payload (JSON)

```jsx
// JSON

{
  "message": {
    "token": "bk3RNwTe3H0:CI2k_HHwgIpoDKCIZvvDMExUdFQ3P1...",
    "notification": {
      "title": "burstcamp",
      "body": "메세지를 어떻게 보내야 할지요"
    },
		"data": {
			"feedUUID": "feedUUID"
		}
  }
}
```

**Comment by NEULiee** [comment]
## 권한

[https://developer.apple.com/documentation/usernotifications/asking_permission_to_use_notifications](https://developer.apple.com/documentation/usernotifications/asking_permission_to_use_notifications)

푸시알림 권한을 꼭 얻어야 한다.

[https://firebase.google.com/docs/cloud-messaging/ios/client](https://firebase.google.com/docs/cloud-messaging/ios/client)

다음과 같은 경우 등록 토큰이 변경될 수 있습니다.

- 앱이 새 기기에서 복원됩니다.
- 사용자가 앱을 제거/재설치합니다.
- 사용자가 앱 데이터를 지웁니다.

![image](https://user-images.githubusercontent.com/39167842/204437941-081f179e-3134-4b8b-b875-6be862aaa145.png)

**Comment by NEULiee** [comment]
### 이슈사항
- 알림이 두번오는 현상
    - 시뮬레이터, 실기기, 탈퇴오류가 이루어낸 FCM 토큰 중복현상

- 12시 16분으로 알림 시간을 맞춰놨는데 아침 6시 16분에 알림이 오는 현상
