### ISSUE TITLE
[유저 정보 수정] 닉네임, 블로그 주소 변경

### ISSUE THREAD

**Issue by Kim-Coding** [boostcampwm-2022/iOS09-burstcamp#30]
## 할 일

- [ ]  닉네임 변경 가능
    - [정책] 닉네임 유효성 검사
- [ ]  블로그 주소 변경 가능
    - 변경 버튼으로 블로그 주소 rss 여부 확인
- [ ]  수정 완료 버튼을 눌러야 변경사항 저장

**Comment by NEULiee** [comment]
[화면]

- 닉네임 변경 가능
    - 닉네임 유효성: 글자가 비어있지 않으면 가능하다.
![Simulator Screen Recording - iPhone 14 Pro - 2022-12-03 at 01 52 51](https://user-images.githubusercontent.com/39167842/205345311-9295f5c8-5b98-4490-a3ad-f7adfb5bbc25.gif)

- 블로그 주소 변경 가능
    - 주소의 유효성 확인
![Simulator Screen Recording - iPhone 14 Pro - 2022-12-03 at 01 55 49](https://user-images.githubusercontent.com/39167842/205345602-74fcbd9b-b862-453d-8af9-f15518b332e6.gif)

**Comment by NEULiee** [comment]
[로직]

수정완료 버튼 클릭시 validation이 통과되면 유저 저장

```Swift
input.finishEditButtonDidTap
    .sink { _ in
        let validationResult = self.validate()
        output.validationResult.send(validationResult)
        if case .validationOK = validationResult {
            self.saveUser()
        }
    }
    .store(in: &cancelBag)

return output
```

- 유저 저장
블로그 타이틀, 프로필 이미지 Storage에 저장 후 URL을 받아온다.
다 받아온 후 user 업데이트 후 이전 화면으로 돌아간다.

```Swift
FireFunctionsManager
    .blogTitle(link: blogURL)
    .catch { _ in Just("") }
    .combineLatest(profilemageURL())
    .sink { blogTitle, profileImageURL in
        FirestoreUser.update(
            userUUID: UserManager.shared.user.userUUID,
            nickname: self.nickname,
            profileImageURL: profileImageURL,
            blogURL: self.blogURL,
            blogTitle: blogTitle
        )
    }
    .store(in: &viewModelCancelBag)
```
