### ISSUE TITLE
[기능] 피드 시간 Formatting

### ISSUE THREAD

**Issue by Kim-Coding** [boostcampwm-2022/iOS09-burstcamp#32]
## 할 일

- [x] 방금 전 (59초까지)
- [x]  1분 전 ~ 59분 전
- [x]  1시간 전 ~ 23시간 전
- [x]  1일 전 ~ 6일 전
- [x]  1년 이전 : m월 d일 ex) 7월 18일 (월과 일 앞에 0붙이지 않음 07월, 05일 x)
- [x] 1년 이후  : yy.mm.dd ex) 21.10.25, 21.05.05 (월과 일 앞에 0붙임)

**Comment by never-better** [comment]
애플에서 제공하는 RelativeDateTimeFormatter가 있긴 한데 커스텀이 안됨   
초는 초단위로 제공됨 ex) 1초전, 5초전   
우리가 원하는 글이랑 안 맞아 우선 배제  

RelativeDateTimeFormatter 사용한 코드

```swift
extension Date {
    static func relativeTime(pubDate: Date) -> String {
        let formatter = RelativeDateTimeFormatter()
        formatter.locale = Locale(identifier: "ko_KR")
        formatter.dateTimeStyle = .named
        let now = Date()
        let relativeDateString = formatter.localizedString(for: pubDate, relativeTo: now)
        return relativeDateString
    }
}
```

**Comment by never-better** [comment]
![스크린샷 2022-11-24 오후 1 20 48](https://user-images.githubusercontent.com/71776532/203693614-0a8f83be-f8e6-4765-b7ce-0f12ee325669.png)

Quick Help 추가
