### ISSUE TITLE
[CI] Github Action을 이용한 Continuous Integration

### ISSUE THREAD

**Issue by sseungmn** [boostcampwm-2022/iOS09-burstcamp#49]
## 할 일

- [ ] Github Action 동작 방법 학습
- [ ] Github Action에서 Lint와 Build Test

## 추가

- [ ] PR 생성시 build test
리뷰후 Merge가 완료된 시점에서 빌드 오류가 발생하는 경우가 빈번함.
이를 방지하기 위해서 PR을 생성했을 때, build test를 해서 Merge가 가능한지 테스트가 필요.

**Comment by never-better** [comment]
Github Action 실패 -> [실패기 바로 확인하기](https://sseungmn.notion.site/Github-Action-e762c9b0c09d4ee59d7c7f1ee2c9f139)

**Comment by sseungmn** [comment]
- [ ] PR 생성시 build test
  - 리뷰후 Merge가 완료된 시점에서 빌드 오류가 발생하는 경우가 빈번함.
  - 이를 방지하기 위해서 PR을 생성했을 때, build test를 해서 Merge가 가능한지 테스트가 필요.
